//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.28 at 05:35:49 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.oracle.com/communications/ncc/2009/05/15/pi", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.oracle.xmlns.communications.ncc._2009._05._15.pi;
